In [3]:
import numpy as np

list_data = [1,2,3]
array = np.array(list_data)

print(array.size)
print(array.dtype)
print(array[2])

3
int32
3


In [5]:
# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

[0 1 2 3]


In [7]:
#4x4크기의 하나의 이차원 배열 생성, 거기 모든 값이 0 으로 설정 되어있고, 모든 값은 실수형이다.
array2 = np.zeros((4,4), dtype = float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#3X3 크기의 하나의 이차원 배열 생성, 거기 모든 값이 '1' 으로 설정 되어있고, 모든 값은 문자형이다.
array3 = np.ones((3,3), dtype=str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [10]:
# 0 부터 9까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0, 10, (4,4))
print(array4)

[[1 3 4 6]
 [9 2 6 9]
 [3 1 3 7]
 [6 0 6 4]]


In [12]:
#평균이 0이고, 표준편차가 1일 표준 정규를 띄는 배열 = 표준 정규분포
array5 = np.random.normal(0, 1, (3,3))
print(array5)

[[ 0.41871067  1.08897696 -1.34877754]
 [-0.10292184  2.59525147  0.24952463]
 [-0.5305157  -0.38187741  0.1993931 ]]


- Numpy 배열 합치기

In [14]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1,array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [19]:
#1차원 함수를 2차원으로 바꾸고 싶다 = reshape함수

array1 = np.array([1,2,3,4,5,6,7,8,9])
array2 = array1.reshape((3,3))

print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)

print(array1)
print(array2)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]


In [23]:
#세로 기준으로 합치기
array3 = np.concatenate([array1,array2], axis=0)

print(array3)


[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [30]:
#나누기 
array = np.arange(8).reshape(2,4)
left, right = np.split(array, [2], axis=1)


print(left.shape)
print(right.shape)
print('------------------')

print(array)
print('------------------')

print(left)
print('------------------')

print(right)

(2, 2)
(2, 2)
------------------
[[0 1 2 3]
 [4 5 6 7]]
------------------
[[0 1]
 [4 5]]
------------------
[[2 3]
 [6 7]]
